# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
keras = tf.keras
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import mean_squared_error
import plotly.offline as pyo
import plotly.graph_objs as go
from math import sqrt
#physical_devices = tf.config.experimental.list_physical_devices()
#print("Num GPUs:", physical_devices)
#tf.config.experimental.set_memory_growth(physical_devices[0], True)

# Importing Data

In [2]:
#confirmed_df = pd.read_csv('time_series_covid19_confirmed_global.csv')
confirmed_df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')

In [3]:
confirmed_df

Province/State         Country/Region        Lat  ...  6/25/20  6/26/20  6/27/20
0              NaN            Afghanistan  33.000000  ...    30175    30451    30616
1              NaN                Albania  41.153300  ...     2192     2269     2330
2              NaN                Algeria  28.033900  ...    12445    12685    12968
3              NaN                Andorra  42.506300  ...      855      855      855
4              NaN                 Angola -11.202700  ...      212      212      259
..             ...                    ...        ...  ...      ...      ...      ...
261            NaN  Sao Tome and Principe   0.186360  ...      711      712      713
262            NaN                  Yemen  15.552727  ...     1076     1089     1103
263            NaN                Comoros -11.645500  ...      272      272      272
264            NaN             Tajikistan  38.861034  ...     5691     5747     5799
265            NaN                Lesotho -29.609988  ...       17       24       24

[266 rows x 162 columns]

# Date Pre-Processing

In [4]:
DAYS_TO_PREDICT = int(input('Enter Number Of Days You Want to Predict : '))  # last days to predict  

confirmed_df = confirmed_df.groupby("Country/Region").sum().reset_index()
Country_confirmed =  confirmed_df['Country/Region'].values
confirmed_df = confirmed_df.drop(['Lat','Long','Country/Region'], axis=1)
confirmed_df = confirmed_df[confirmed_df.columns].T
confirmed_df.columns = Country_confirmed                                    
compare_confirmed_df=confirmed_df.iloc[-DAYS_TO_PREDICT-1:,:]                 # last days to predict
confirmed_df= confirmed_df.iloc[:-DAYS_TO_PREDICT,:]                        # last days to predict

Date_index = confirmed_df.index
confirmed_df = confirmed_df.diff().fillna(0)
compare_confirmed_df = compare_confirmed_df.diff().dropna(0)
confirmed_df = confirmed_df.abs()

confirmed_df


Enter Number Of Days You Want to Predict : 5


Afghanistan  Albania  Algeria  ...  Yemen  Zambia  Zimbabwe
1/22/20          0.0      0.0      0.0  ...    0.0     0.0       0.0
1/23/20          0.0      0.0      0.0  ...    0.0     0.0       0.0
1/24/20          0.0      0.0      0.0  ...    0.0     0.0       0.0
1/25/20          0.0      0.0      0.0  ...    0.0     0.0       0.0
1/26/20          0.0      0.0      0.0  ...    0.0     0.0       0.0
...              ...      ...      ...  ...    ...     ...       ...
6/18/20        658.0     66.0    117.0  ...    7.0     4.0      62.0
6/19/20        346.0     50.0    119.0  ...   10.0    14.0      16.0
6/20/20        546.0     53.0    127.0  ...    3.0     0.0       0.0
6/21/20        409.0     71.0    140.0  ...   19.0     0.0      10.0
6/22/20        324.0     33.0    149.0  ...   26.0     0.0      23.0

[153 rows x 188 columns]

## Enter countries you want to forecast


In [5]:
i = int(input('Number of countries you want to consider : '))
countries = [input('Enter country You Want to forecast : ') for i in range(i)]

Number of countries you want to consider : 3
Enter country You Want to forecast : Germany
Enter country You Want to forecast : Italy
Enter country You Want to forecast : China


In [6]:
countries

['Germany', 'Italy', 'China']

In [7]:
confirmed_df = confirmed_df.loc[:,countries]   
compare_confirmed_df = compare_confirmed_df.loc[:,countries]  # last days to predict 

In [8]:
confirmed_df

Germany  Italy  China
1/22/20      0.0    0.0    0.0
1/23/20      0.0    0.0   95.0
1/24/20      0.0    0.0  277.0
1/25/20      0.0    0.0  486.0
1/26/20      0.0    0.0  669.0
...          ...    ...    ...
6/18/20   1213.0  331.0   36.0
6/19/20    482.0  148.0    0.0
6/20/20    371.0  264.0   59.0
6/21/20    602.0  224.0   19.0
6/22/20    496.0  221.0   52.0

[153 rows x 3 columns]

# Scalling the data

In [9]:
sc = RobustScaler()
confirmed_df_scaled = sc.fit_transform(confirmed_df)
confirmed_df_scaled = pd.DataFrame(confirmed_df_scaled)
confirmed_df_scaled

0         1         2
0   -0.314322 -0.260580 -0.252577
1   -0.314322 -0.260580  0.237113
2   -0.314322 -0.260580  1.175258
3   -0.314322 -0.260580  2.252577
4   -0.314322 -0.260580  3.195876
..        ...       ...       ...
148  0.454373 -0.130878 -0.067010
149 -0.008872 -0.202586 -0.252577
150 -0.079214 -0.157132  0.051546
151  0.067174 -0.172806 -0.154639
152  0.000000 -0.173981  0.015464

[153 rows x 3 columns]

# Enter the number of days you want to predict

In [10]:
# DAYS_TO_PREDICT = int(input('Enter Number Of Days You Want to Predict : ')) # when future forecast is done. 
predict_confirm_index = pd.date_range(start=Date_index[-1],periods=DAYS_TO_PREDICT + 1,closed='right')
predict_confirm_index = predict_confirm_index.strftime('%Y/%m/%d')

# Creating class for building model

In [11]:
class Corona_Confirmed_model():
    def create_dataset(self, dataset, time_steps=1, column = 0):
        dataX, dataY = [], []
        for i in range(len(dataset)-time_steps-1):
            a = dataset[i:(i+time_steps), column]
            dataX.append(a)
            dataY.append(dataset[i + time_steps, column])
        return np.array(dataX), np.array(dataY)

    def Model(self,dframe,column):
        df = dframe.values
        df = df.astype('float32')
        
        time_steps = 1
        trainX, trainY = self.create_dataset(df, time_steps, column)
        trainX = np.reshape(trainX, (trainX.shape[0],1,trainX.shape[1]))
        
        
        keras.backend.clear_session()
        tf.random.set_seed(42)
        np.random.seed(42)
        confirm_model = keras.models.Sequential([
            keras.layers.InputLayer(input_shape=[None, 1]),
            keras.layers.Conv1D(filters=16, kernel_size=2,
                      strides=1, padding="causal",
                      activation="relu",
                      ),
            keras.layers.LSTM(30,kernel_initializer = 'he_normal',
                              return_sequences = True),
            keras.layers.LSTM(30,kernel_initializer = 'he_normal',
                              return_sequences = True),
            keras.layers.Dense(15,kernel_initializer = 'he_normal',
                                             activation = 'relu'),
            keras.layers.Dense(15,kernel_initializer = 'he_normal',
                                             activation = 'relu'),
            keras.layers.Dense(1,activation = 'linear',kernel_initializer = 'he_normal'),
            keras.layers.Lambda(lambda x: x * 200)
             ])
        
        optimizer = keras.optimizers.Adadelta(lr=0.001)
        
        confirm_model.compile(loss=['mae'],optimizer=optimizer)   
                
        confirm_model.fit(trainX, trainY, epochs=100,
                          batch_size = 10,verbose = 0)
        

        confirm_test_seq  = trainX[-1:]
        confirm_test_seq = confirm_test_seq
        confirm_test_seq = confirm_test_seq.reshape(len(confirm_test_seq), time_steps, 1)
        confirm_preds = []
        
        for _ in range (DAYS_TO_PREDICT):
            confirm_pred = confirm_model.predict(confirm_test_seq)
            confirm_preds.append(confirm_pred)
            confirm_new_seq = confirm_pred
            confirm_test_seq = confirm_new_seq
            confirm_test_seq = confirm_test_seq.reshape(len(confirm_test_seq ), time_steps, 1)

        

        return confirm_preds

# Calling the class and predicting the cases for every individual country

In [12]:
NN = Corona_Confirmed_model()
confirm_predictions = []
for i in range(len(countries)):
  result = NN.Model(confirmed_df_scaled,i) 
  confirm_predictions.append(result)
confirm_predictions        

[[array([[[-0.2000331]]], dtype=float32),
  array([[[-0.27865452]]], dtype=float32),
  array([[[-0.3014042]]], dtype=float32),
  array([[[-0.30916765]]], dtype=float32),
  array([[[-0.31194478]]], dtype=float32)],
 [array([[[-0.18010719]]], dtype=float32),
  array([[[-0.19862218]]], dtype=float32),
  array([[[-0.21365625]]], dtype=float32),
  array([[[-0.22594324]]], dtype=float32),
  array([[[-0.23604085]]], dtype=float32)],
 [array([[[0.01383077]]], dtype=float32),
  array([[[0.01103138]]], dtype=float32),
  array([[[0.00360775]]], dtype=float32),
  array([[[-0.01031718]]], dtype=float32),
  array([[[-0.05513616]]], dtype=float32)]]

# Processing the predicted data

In [13]:
confirm_predictions = (np.array(confirm_predictions).transpose())
confirm_predictions = confirm_predictions.reshape(((DAYS_TO_PREDICT),len(countries)))
confirm_predictions = sc.inverse_transform(confirm_predictions)
confirm_predictions = pd.DataFrame(confirm_predictions)
confirm_predictions = confirm_predictions.abs()
confirm_predictions['Dates'] = predict_confirm_index
confirm_predictions.set_index('Dates', inplace = True)
confirm_predictions.columns = countries
confirm_predictions.head()

Germany       Italy      China
Dates                                        
2020/06/23  180.347778  205.366455  51.683170
2020/06/24   56.283173  158.116180  51.140087
2020/06/25   20.384155  119.749268  49.699905
2020/06/26    8.133453   88.392883  46.998466
2020/06/27    3.751129   62.623779  38.303585

# Visualizing The Confirmed Cases For A Country As Per The User's Choice

### List of Infected Countries

In [14]:
Infected_Countries = pd.DataFrame(countries)
Infected_Countries.columns = ['Countries']
pd.set_option("max_rows", None)
Infected_Countries

Countries
0   Germany
1     Italy
2     China

### Select The Country

In [15]:
Country =input('Enter the name of the country from above list you would like to see the daily cases till now : ')

Enter the name of the country from above list you would like to see the daily cases till now : Italy


## Till Date Confirm Cases on daily basis of coronavirus

In [16]:
fig = go.Figure()
fig.update_layout(template='plotly_dark',title={'text': 'Confirmed Daily Cases','y':0.9,'x':0.5,'xanchor': 'center',
                                                'yanchor': 'top'},
                    xaxis_title = "Dates",
                    yaxis_title="Number Of Cases",
                     )
fig.add_trace(go.Scatter(x=confirmed_df.index, 
                         y=confirmed_df[Country],
                         mode='lines+markers',
                         line=dict(color='blue', width=2)))

## Predictions of confirmed cases of coronavirus

In [17]:
fig = go.Figure()
fig.update_layout(template='plotly_dark',title={'text': 'Confirmed Cases Predictions','y':0.9,'x':0.5,'xanchor': 'center',
                                                'yanchor': 'top'},
    xaxis_title = "Dates",
    yaxis_title="Number Of Cases")
fig.update_xaxes(tickangle=90, showticklabels = True, type = 'category')
fig.add_trace(go.Scatter(x=confirm_predictions.index, 
                         y=confirm_predictions[Country],
                         mode='lines+markers',
                         line=dict(color='yellow', width=2)))

In [18]:
#pd.concat((confirmed_df,confirm_predictions))

In [19]:
fig = go.Figure()
fig.update_layout(template='plotly_dark',title={'text': 'Confirmed Cases Predictions','y':0.9,'x':0.5,'xanchor': 'center',
                                                'yanchor': 'top'},
    xaxis_title = "Dates",
    yaxis_title="Number Of Cases")
fig.update_xaxes(tickangle=90, showticklabels = True, type = 'category')
fig.add_trace(go.Scatter(x=pd.concat((confirmed_df,confirm_predictions)).index, 
                         y=pd.concat((confirmed_df,confirm_predictions))[Country],
                         mode='lines+markers',
                         line=dict(color='red', width=2)))

## Root mean square error between last days predictions(only for comment last days to predict)

In [20]:
compare_confirmed_df

Germany  Italy  China
6/23/20    712.0  113.0   29.0
6/24/20    391.0  577.0   20.0
6/25/20    500.0  296.0   28.0
6/26/20    665.0  255.0   24.0
6/27/20    422.0  175.0   18.0

In [21]:
confirm_predictions

Germany       Italy      China
Dates                                        
2020/06/23  180.347778  205.366455  51.683170
2020/06/24   56.283173  158.116180  51.140087
2020/06/25   20.384155  119.749268  49.699905
2020/06/26    8.133453   88.392883  46.998466
2020/06/27    3.751129   62.623779  38.303585

In [22]:
for country in countries:
  realVals = compare_confirmed_df[country]
  predictedVals = confirm_predictions[country]
  rmse = sqrt(mean_squared_error(realVals, predictedVals))
  print('RMSE for {} :'.format(country),rmse )

RMSE for Germany : 496.21095834719307
RMSE for Italy : 226.0291500330374
RMSE for China : 24.067746729389224
